// Hand-written NinjaScript indicator -- NOT auto-generated by the packaging
// pipeline (src/Packaging/SamplePayloadFactory.cs only emits empty starter
// stubs for names listed in config/deploy-settings.json's indicatorNames;
// adding "PositionExporter" there would overwrite this file with a blank
// stub on the next `package-nt8.ps1` run). Import manually for now:
//   NinjaTrader 8 > Tools > New > NinjaScript Editor > Indicators >
//   right-click > "Add existing item..." and select this file,
// or copy it directly into "Documents\NinjaTrader 8\bin\Custom\Indicators".
//
// Purpose: NinjaTrader 8's Automated Trading Interface (ATI) is command-only
// -- it can submit PLACE/CANCEL order files but exposes no position/fill
// data back out. This indicator watches one account's positions and writes
// a JSON snapshot on every change, which
// northstar/copier/nt8_bridge/position_reader.py tails to answer
// GET /positions. See docs/concepts/broker-axis.md in the Northstar repo.
//
// Snapshot shape (must match PositionSnapshotReader.read()'s expectations):
//   {
//     "written_at": <unix epoch seconds, float>,
//     "positions": [
//       {"symbol": "MNQ", "quantity": 2, "avg_price": 18500.25, "ts": <epoch>}
//     ]
//   }
// Only non-flat positions are included. quantity is signed: positive = long,
// negative = short.

using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using NinjaTrader.Cbi;

namespace NinjaTrader.NinjaScript.Indicators
{
    public class PositionExporter : Indicator
    {
        private Account _account;

        [NinjaScriptProperty]
        public string AccountName { get; set; } = "Sim101";

        [NinjaScriptProperty]
        public string SnapshotPath { get; set; } =
            @"C:\NorthstarBridge\positions.json";

        protected override void OnStateChange()
        {
            if (State == State.SetDefaults)
            {
                Name = "PositionExporter";
                Description =
                    "Writes a JSON position snapshot for the Northstar NT8 ATI bridge. "
                    + "Set AccountName to the exact NT8 account name and SnapshotPath to "
                    + "the file northstar/copier/nt8_bridge reads.";
                Calculate = Calculate.OnBarClose;
                IsOverlay = true;
                IsAutoScale = false;
            }
            else if (State == State.Configure)
            {
                // No bar series subscription needed; this indicator only
                // observes account-level position events.
            }
            else if (State == State.DataLoaded)
            {
                _account = Account.All.FirstOrDefault(a =>
                    string.Equals(a.Name, AccountName, StringComparison.OrdinalIgnoreCase));

                if (_account == null)
                {
                    Draw.TextFixed(
                        this,
                        "PositionExporterError",
                        $"PositionExporter: account '{AccountName}' not found",
                        NinjaTrader.Gui.Chart.TextPosition.BottomRight);
                    return;
                }

                _account.PositionUpdate += OnAccountPositionUpdate;
                _account.ExecutionUpdate += OnAccountExecutionUpdate;

                // Write an initial snapshot immediately so the bridge doesn't
                // have to wait for the first position change after startup.
                WriteSnapshot();
            }
            else if (State == State.Terminated)
            {
                if (_account != null)
                {
                    _account.PositionUpdate -= OnAccountPositionUpdate;
                    _account.ExecutionUpdate -= OnAccountExecutionUpdate;
                }
            }
        }

        protected override void OnBarUpdate()
        {
            // Intentionally empty: this indicator does not draw on bars, it
            // only reacts to account position/execution events below.
        }

        private void OnAccountPositionUpdate(object sender, PositionEventArgs e)
        {
            WriteSnapshot();
        }

        private void OnAccountExecutionUpdate(object sender, ExecutionEventArgs e)
        {
            WriteSnapshot();
        }

        private void WriteSnapshot()
        {
            if (_account == null)
            {
                return;
            }

            try
            {
                double writtenAt = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds() / 1000.0;

                var positionEntries = _account.Positions
                    .Where(p => p.MarketPosition != MarketPosition.Flat && p.Quantity != 0)
                    .Select(p =>
                    {
                        int signedQuantity = p.MarketPosition == MarketPosition.Short
                            ? -p.Quantity
                            : p.Quantity;
                        return FormatPositionEntry(
                            p.Instrument.MasterInstrument.Name,
                            signedQuantity,
                            p.AveragePrice,
                            writtenAt);
                    });

                var json = new StringBuilder();
                json.Append("{\"written_at\":");
                json.Append(writtenAt.ToString("F3", CultureInfo.InvariantCulture));
                json.Append(",\"positions\":[");
                json.Append(string.Join(",", positionEntries));
                json.Append("]}");

                string directory = Path.GetDirectoryName(SnapshotPath);
                if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
                {
                    Directory.CreateDirectory(directory);
                }

                string tempPath = SnapshotPath + ".tmp";
                File.WriteAllText(tempPath, json.ToString(), Encoding.UTF8);
                File.Delete(SnapshotPath); // File.Move throws if destination exists on older runtimes
                File.Move(tempPath, SnapshotPath);
            }
            catch (Exception ex)
            {
                Draw.TextFixed(
                    this,
                    "PositionExporterError",
                    $"PositionExporter write failed: {ex.Message}",
                    NinjaTrader.Gui.Chart.TextPosition.BottomRight);
            }
        }

        private static string FormatPositionEntry(
            string symbol, int quantity, double avgPrice, double ts)
        {
            string escapedSymbol = symbol.Replace("\\", "\\\\").Replace("\"", "\\\"");
            return "{\"symbol\":\"" + escapedSymbol + "\","
                + "\"quantity\":" + quantity.ToString(CultureInfo.InvariantCulture) + ","
                + "\"avg_price\":" + avgPrice.ToString("F5", CultureInfo.InvariantCulture) + ","
                + "\"ts\":" + ts.ToString("F3", CultureInfo.InvariantCulture) + "}";
        }
    }
}
