name: ci

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-package:
    uses: ./.github/workflows/_build-package.yml
    with:
      package_version: 1.0.0
      upload_artifact: true
      artifact_name: zerotouch-package
